default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  user: postgres
  password: mysecretpassword

development:
  <<: *default
  database: civic_development

test:
  <<: *default
  database: civic_test
  <% if ENV['TRAVIS_BUILD'] %>
  username: postgres
  <% end %>

production:
  <<: *default
  database: civic
